# Artifact Registry path: ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/ergo-platform-frontend:$COMMIT_SHA
# _REGION controls the AR location (e.g., europe-west4); _REPO controls the AR repository name.

substitutions:
  _REGION: europe-west4
  _REPO: ergo-frontend

steps:
  # build
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/ergo-platform-frontend:$COMMIT_SHA
      - .
  # push
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/ergo-platform-frontend:$COMMIT_SHA
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'ergo-platform-frontend', '--image', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/ergo-platform-frontend:$COMMIT_SHA', '--region', 'europe-west4', '--set-secrets', 'OPENAI_API_KEY=OPENAI_API_KEY:latest']

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/ergo-platform-frontend:$COMMIT_SHA

timeout: 1900s
